---
title: "Transformation of Features with Package mlfeaturer"
author: "Thomas Petzoldt"
date: "`r Sys.Date()`"
bibliography: bib.bib
vignette: >
  %\VignetteIndexEntry{Transformation of Features with Package mlfeaturer}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---


```{r opts, echo = FALSE, message = FALSE}
library("dplyr")
```



Introduction
============

# mlfeaturer

## Machine Learning: Feature Engineering for Regression Models

Package **mlfeaturer** aims to provide data manipulation support for a
subset of machine learning problems, currently regression problems
with multiple input variables $x$ and a single input variable and a
single input variable $y$. A typical initial task is to transform and
scale the variables, split them into training and test sets, and then
and, after model fitting, compare the model outputs with the original
data, with the test data, and with test data, and with independent new
data.

It fills a gap between a style of creating a large number of
intermediate data frames and variables, as found in some introductory
tutorials, and full-fledged packages like
[caret](https://topepo.github.io/caret/),
[recipes](https://recipes.tidymodels.org/) or
[mlr3](https://mlr3.mlr-org.com/).

It uses S4 object orientation, is intentionally simple and mostly
developed for our own tasks.

Installation
============

```
remotes::install_.packages_github("https://github.com/tpetzoldt/mlfeaturer")
```

Example
=======

Lorem ipsum ...



Acknowledgments
===============

Many thanks to the R Core Team
[@RCore2024] for developing and maintaining **R**. This documentation
was written using **knitr** [@knitr] and **rmarkdown**
[@rmarkdown].


References
==========

<div id="refs"></div>

----

**Copyright and original author:** [tpetzoldt](https://github.com/tpetzoldt)

